function perturb_Verf(t)
global Source_V Amplitude_V Frequency_V ...
       Source_P1 Amplitude_P1 Frequency_P1 pm01 ...
       Exc vref0 intstep VP_nos VQ_nos tcorr ...
       P0 Q0 PQ_std PQ Syn 

     Exc.vref0 = vref0*(1 + Amplitude_V*sin(2*pi*Frequency_V*t));
end